export const getColor = (themeColor) => ({
    mode: themeColor.Mode,
  
    Base: themeColor.Base,
    Base_01: themeColor.Base_01,
    Base_02: themeColor.Base_02,
    Base_03: themeColor.Base_03,
    Base_04: themeColor.Base_04,
    Base_05: themeColor.Base_05,
    Base_06: themeColor.Base_06,
    Base_07: themeColor.Base_07,
    
    
    Base_09: themeColor.Base_09,
    Base_10: themeColor.Base_10,
    Base_11: themeColor.Base_11,
    Base_12: themeColor.Base_12,
    Base_13: themeColor.Base_13,
    Base_14: themeColor.Base_14,
    Base_15: themeColor.Base_15,
    Base_16: themeColor.Base_16,
    Base_17: themeColor.Base_17,
    Base_18: themeColor.Base_18,
    Base_19: themeColor.Base_19,
    Base_20: themeColor.Base_20,
    
    Base_21: themeColor.Base_21,
    Base_22: themeColor.Base_22,
    Base_23: themeColor.Base_23,
    Base_24: themeColor.Base_24,
    Base_25: themeColor.Base_25,
    Base_26: themeColor.Base_26,
    Base_27: themeColor.Base_27,
    Base_28: themeColor.Base_28,
    Base_29: themeColor.Base_29,
    Base_30: themeColor.Base_30,
    Base_31: themeColor.Base_31,
    Base_32: themeColor.Base_32,
    Base_33: themeColor.Base_33,
    Base_34: themeColor.Base_34,
  
    Base_35: themeColor.Base_35,
    Base_36: themeColor.Base_36,
    Base_37: themeColor.Base_37,
    Base_38: themeColor.Base_38,
    Base_39: themeColor.Base_39,
    Base_40: themeColor.Base_40,
    Base_41: themeColor.Base_41,
    Base_42: themeColor.Base_42,
    Base_43: themeColor.Base_43,
  
    //Primary Colors
    Primary: themeColor.Primary,
    Primary_01: themeColor.Primary_01,
    Primary_02: themeColor.Primary_02,
    Primary_03: themeColor.Primary_03,
    Primary_04: themeColor.Primary_04,
    Primary_05: themeColor.Primary_05,
    Primary_06:themeColor.Primary_06,
    Primary_07:themeColor.Primary_07,
  
    Primary_Two: themeColor.Primary_Two,
    Primary_Two_01: themeColor.Primary_Two_01,
    Primary_Two_02: themeColor.Primary_Two_02,
    Primary_Two_03: themeColor.Primary_Two_03,
    Primary_Two_04: themeColor.Primary_Two_04,
    Primary_Two_05: themeColor.Primary_Two_05,
    Primary_Two_06: themeColor.Primary_Two_06,
    Primary_Two_07: themeColor.Primary_Two_07,
  
  
    //Secondary Colors
    Secondary: themeColor.Secondary,
    Secondary_01: themeColor.Secondary_01,
    Secondary_02: themeColor.Secondary_02,
    Secondary_03: themeColor.Secondary_03,
    Secondary_04: themeColor.Secondary_04,
    Secondary_05: themeColor.Secondary_05,
    Secondary_06: themeColor.Secondary_06,
  
    Tertiary:themeColor.Tertiary,
    Tertiary_01:themeColor.Tertiary_01,
    Tertiary_02:themeColor.Tertiary_02,
    Tertiary_03:themeColor.Tertiary_03,
    Tertiary_04:themeColor.Tertiary_04,
    Tertiary_05:themeColor.Tertiary_05,
    Tertiary_06:themeColor.Tertiary_06,
  
    Extra:themeColor.Extra,
    Extra_01:themeColor.Extra_01,
    Extra_02:themeColor.Extra_02,
    Extra_03:themeColor.Extra_03,
    
    });
    
    export const getAntTheme = (themeColor) => ({
      controlHeightSX: 30,
      controlHeightSM: 40,
      controlHeightLG: 50,
      fontSize: 16,
      fontFamily: 'Poppins',
      borderRadius: 8,
      buttonPaddingHorizontal: 40,
      paddingContentHorizontal: 20,
      paddingXS: 40,
    });
    export const Components = (themeColor) => ({
      Button: {
          // colorBgContainer:"#000",
          // colorBgContainerDisabled:"#000",
          // colorBgTextActive:"#000",
          // colorBgTextHover:"#000",
          // colorBorder:,
          // colorError:,
          // colorErrorActive:,
          // colorErrorBg:,
          // colorErrorBorderHover:,
          // colorErrorHover:,
          // colorErrorOutline:,
          // colorLink:,
          // colorLinkActive:,
          // colorLinkHover:,
          // colorPrimary:,
          // colorPrimaryActive	:,
          // colorPrimaryBorder:,
          // colorPrimaryHover:,
          // colorText:,
          // colorTextDisabled:,
          // colorTextLightSolid:,
  
        
      },
      Divider: {
        colorSplit: themeColor.Base_13,
      },
      Checkbox: {
        // colorPrimary:themeColor.Base_13,
        colorBgContainer: themeColor.Base_19,
        colorBorder: themeColor.Base_01,
        colorText: themeColor.Base_01,
        borderRadius: 2,
        borderRadiusSM: 2,
        controlInteractiveSize: 16,
        paddingXS: 8,
      },
      Typography: {
        colorText: themeColor.Base_01,
        fontSizeHeading1: 32,
        fontSizeHeading2: 28,
        fontSizeHeading3: 24,
        fontSizeHeading4: 16,
        fontSizeHeading5: 14,
        marginXS: 0,
        marginLG: 0,
        marginXXS: 0,
        fontFamilyCode: 'poppins',
      },
      Table: {
        borderRadius: 0,
        borderRadiusLG: 0,
        colorBgContainer: themeColor.Base_19,
        colorBorderSecondary: themeColor.Base_13,
        colorText: themeColor.Base_01,
        colorTextHeading: themeColor.Base_01,
        fontSize: 12,
        fontSizeSM: 12,
        fontWeightStrong: 400,
        lineHeight: '18px',
        padding: 10,
        paddingContentVerticalLG: 11,
        margin: 0,
      },
      Tag: {
        borderRadiusSM: 11,
        fontSize: 11,
        fontSizeSM: 11,
      },
      Tooltip: {
        colorBgSpotlight: themeColor.Base_20,
        colorText: themeColor.Base_13,
        borderRadius: 2,
        borderRadiusOuter: 1.5,
        fontSize: 12,
        sizePopupArrow: 15,
        paddingXS: 8,
        paddingSM: 10,
        lineHeight: 2,
      },
      Menu: {
        colorBgContainer: themeColor.Color_01,
        colorText: themeColor.WhiteColor,
      },
      Tabs: {
        colorBgContainer: themeColor.Base_20,
        colorFillAlter: themeColor.Base_19,
        colorText: themeColor.WhiteColor,
        borderRadius: 0,
        borderRadiusLG: 0,
        colorPrimary: themeColor.WhiteColor,
        colorPrimaryActive: themeColor.WhiteColor,
        colorPrimaryHover: themeColor.WhiteColor,
        fontSize: 12,
        fontSizeLG: 12,
        fontSizeSM: 12,
        lineHeight: 1.5,
        lineWidth: 1,
        margin: 0,
        controlHeight: 35,
        controlHeightLG: 35,
        padding: 12,
        colorBorder: themeColor.Base_13,
        colorBorderSecondary: themeColor.Base_13,
      },
    });